name: Linux

on: [push, pull_request]

jobs:
  gcc10_cpp20:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install_deps
      run: |
           sudo apt update
           sudo apt install gcc-10 g++-10
           curl -L https://dl.bintray.com/boostorg/release/1.76.0/source/boost_1_76_0.tar.gz --output boost_1_76_0.tar.gz
           tar -xzf boost_1_76_0.tar.gz
      shell: bash
    - name: cmake
      run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_STANDARD_REQUIRED=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCOMA_ENABLE_TESTS=1 -DCOMA_TESTS_BOOST_INC_DIR="$PWD/boost_1_76_0"
      env:
        CC:  gcc-10
        CXX: g++-10
    - name: build
      run: cmake --build build --parallel 8
    - name: test
      run: cd build; ctest --output-on-failure

  gcc10_cpp11:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install_deps
      run: |
           sudo apt update
           sudo apt install gcc-10 g++-10
           curl -L https://dl.bintray.com/boostorg/release/1.76.0/source/boost_1_76_0.tar.gz --output boost_1_76_0.tar.gz
           tar -xzf boost_1_76_0.tar.gz
      shell: bash
    - name: cmake
      run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=11 -DCMAKE_CXX_STANDARD_REQUIRED=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCOMA_ENABLE_TESTS=1 -DCOMA_TESTS_BOOST_INC_DIR="$PWD/boost_1_76_0"
      env:
        CC:  gcc-10
        CXX: g++-10
    - name: build
      run: cmake --build build --parallel 8
    - name: test
      run: cd build; ctest --output-on-failure

  gcc10_cpp11_boost170:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install_deps
      run: |
           sudo apt update
           sudo apt install gcc-10 g++-10
           curl -L https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.gz --output boost_1_70_0.tar.gz
           tar -xzf boost_1_70_0.tar.gz
      shell: bash
    - name: cmake
      run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=11 -DCMAKE_CXX_STANDARD_REQUIRED=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCOMA_ENABLE_TESTS=1 -DCOMA_TESTS_BOOST_INC_DIR="$PWD/boost_1_70_0"
      env:
        CC:  gcc-10
        CXX: g++-10
    - name: build
      run: cmake --build build --parallel 8
    - name: test
      run: cd build; ctest --output-on-failure

  clang11_cpp20:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install_deps
      run: |
           sudo apt update
           sudo apt install clang-11
           curl -L https://dl.bintray.com/boostorg/release/1.76.0/source/boost_1_76_0.tar.gz --output boost_1_76_0.tar.gz
           tar -xzf boost_1_76_0.tar.gz
      shell: bash
    - name: cmake
      run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_STANDARD_REQUIRED=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCOMA_ENABLE_TESTS=1 -DCOMA_TESTS_BOOST_INC_DIR="$PWD/boost_1_76_0"
      env:
        CC:  clang-11
        CXX: clang++-11
    - name: build
      run: cmake --build build --parallel 8
    - name: test
      run: cd build; ctest --output-on-failure

